name: cmd
description: The cmd package is a command line tool for Flutter Developers that is used to run the most common shell/bash commands via pre-built scripts.

version: 0.0.13
homepage: https://github.com/UsamaSarwar/flutter/tree/main/pub/cmd

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

screenshots:
  - description: "© Telegram"
    path: assets/logo.webp

topics:
  - flutter
  - cmd
  - command
  - shell
  - bash

flutter: