name: cmd
description: A comprehensive command line toolkit for Flutter developers with interactive scripts, app signing utilities, performance testing, and platform-specific tools. Includes a modern dialer interface for easy script management.

version: 1.0.0
homepage: https://github.com/UsamaSarwar/flutter/tree/main/pub/cmd

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

screenshots:
  - description: "Flutter CMD Toolkit"
    path: assets/logo.webp

topics:
  - flutter
  - cmd
  - build
  - testing
  - developer-tools