name: telegram
description: A comprehensive Telegram utility for Flutter with URL schemes, Bot API integration, media sharing, chat management, and Web App support.
version: 1.0.0
homepage: https://www.usama.dev
repository: https://github.com/UsamaSarwar/flutter/tree/main/pub/telegram

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.1
  http: ^1.4.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  cmd: ^1.0.1

flutter:
  uses-material-design: true

screenshots:
  - description: "© Telegram Flutter Package"
    path: assets/logo.webp

topics:
  - telegram
  - bot-api
  - messaging
  - url-schemes
  - media-sharing