name: telegram
description: A simple and light weight utility for sending message via Telegram...
version: 0.0.9
homepage: https://www.usama.dev
repository: https://github.com/UsamaSarwar/flutter/tree/main/pub/telegram

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  cmd: ^0.0.13

flutter:
  uses-material-design: true

screenshots:
  - description: "© Telegram"
    path: assets/logo.webp

topics:
  - telegram
  - message
  - send
  - chat